### ISSUE TITLE
Feature request Average Pooling and Min Pooling support

### ISSUE THREAD

**Issue by victorromeo** [uTensor/utensor_cgen#134]
MinPooling appears to be only partially implemented.  Avg Pooling is not implemented at all.
May we add? Thanks

**Comment by victorromeo** [comment]
See pull request #135

uTensor implementation still in progress

**Comment by dboyliao** [comment]
Just to correct your statement a bit, `AvgPool` and `MinPool` is supported in `uTensor` runtime at `develop` branch.

https://github.com/uTensor/uTensor/blob/develop/src/uTensor/ops/Convolution.hpp#L287-L294

And yes, it haven't added to `utensor_cgen`, which is different from `uTensor` runtime but a code generator for the runtime.

**Comment by dboyliao** [comment]
PR #135 merged.
Closing issue.
