### ISSUE TITLE
pipenv defaults to >= Python 3.6

### ISSUE THREAD

**Issue by mbartling** [uTensor/utensor_cgen#5]
We need to default this to Python 2.7 to be compliant with mbed.

**Comment by dboyliao** [comment]
But code generator does not need `mbed` cli.
Why should we impose such requirement?

**Comment by mbartling** [comment]
because most industry settings comply with 2.6 or 2.7. And a lot of these guys do not have python 3 on their systems and or don't know how to properly work with multiple python versions.

**Comment by dboyliao** [comment]
I've add `requirements.txt` in the repo.
And I tested with virtualenv already and it's working.
I think it's not a issue anymore.

**Comment by dboyliao** [comment]
@mbartling 
Closing it.
If you see any other issue related to this issue, you can reopen it later.
